### ISSUE TITLE
Isobaric labels support

### ISSUE THREAD

**Issue by prvst** [jpquast/protti#146]
Hi. Firstly, I find your project very interesting. My compliments to the developers for keeping the source extremely organize, and for following the tidyverse "philosophy".
Here's my question. Can I process data labelled with TMT or iTRAQ? If so, could you give me some pointers?

Thanks, and well done!

**Comment by jpquast** [comment]
Hi Felipe, thanks a lot for your question and the praise! 
Unfortunately, we have no TMT or iTRAQ specific analysis pipelines implemented at the moment. Of course you can still use some of our functions (mainly post analysis, e.g. GO enrichment, network analysis etc.) for labelled data but we do not have any specific functions for the purpose. At the moment I am not planing to implement any pipeline for labelled data as I am not very experienced with this.
