### ISSUE TITLE
Question - adding condition to bottom-up data results in NA column

### ISSUE THREAD

**Issue by bmroger2** [jpquast/protti#154]
Hello, 

Your vignette is rather easy to follow. I have a binary comparison set of PD data with 4 replicates of treatment and 3 replicates of a DMSO control exported as a CSV. In the [input preparation workflow](https://jpquast.github.io/protti/articles/input_preparation_workflow.html) I can follow each step except the last one :

pd_prot_long_annotated <- pd_prot_long %>% 
  left_join(y = annotation, by = "file_name")

A glimpse of the pd_prot_long_annotated shows the condition column as 'NA'. This seems to be unintended.
<img width="1280" alt="Screen Shot 2021-07-20 at 8 52 20 PM" src="https://user-images.githubusercontent.com/52229393/126428125-1c91ff96-fda0-4275-8b69-c24ec1e321ce.png">

**Comment by dschust-r** [comment]
Hi Bryan, 

Thank you for your question! Could you maybe provide me with more information on what your data frames (both the pd_prot_long and the annotation df) look like exactly (column names and information contained in your columns)? This would really help me to see where the issue might be. 

In theory, the joining should work if both data frames (i.e. the one you want to merge with the annotation and the annotation data frame) contain exactly the same file names in a column called "file_name" in both data frames. 

Just an example: 

```
# create example data frame with abundances and file names

abundance <- c(1,2,3,1,3,7)

file_name <- c(
  "sample1",
  "sample2",
  "sample3",
  "sample4",
  "sample5",
  "sample6"
)

data <- data.frame(file_name, abundance)

# create annotation data frame

condition <- c(
  "control",
  "control",
  "control",
  "treated",
  "treated",
  "treated"
)
annotation <- data.frame(file_name, condition)

# join both data frames

data_annotated <- data %>%
  left_join(annotation, by = "file_name")
```

`data_annotated` will then look like this: 

```
view(data_annotated)

> data_annotated
  file_name abundance condition
1   sample1         1   control
2   sample2         2   control
3   sample3         3   control
4   sample4         1   treated
5   sample5         3   treated
6   sample6         7   treated

```
All the best, 
Dina

**Comment by dschust-r** [comment]
I just had another look at your `file_name`  vector that you use to make the annotation data frame. To me it looks like your file names in your annotation data frame and `pd_prot_long` do not match exactly. 

E.g. in `pd_prot_long` your first file name is `"abundances_normalized_dmso_1"` whereas in your annotation data frame this is `"Abundances Normalized DMSO 1"`. 

If you change it to snake case (`"abundances_normalized_dmso_1"`) in your annotation data frame this should work. 

Please let me know if that helped you fix the issue. 

All the best, 
Dina

**Comment by bmroger2** [comment]
Dina,

You're absolutely correct and I am embarrassed. This code works perfectly fine!

Thank you for the help and for designing such an easy to follow vignette for beginners in R!

Kind regards,
Bryan
