### ISSUE TITLE
NOTICE: plan(multiprocess) of future is deprecated

### ISSUE THREAD

**Issue by HenrikBengtsson** [jpquast/protti#160]
Hi.

This is a friendly reminder that [`plan(multiprocess)`](https://future.futureverse.org/reference/multiprocess.html) of the [**future**](https://cran.r-project.org/package=future) package is _deprecated_ since **future** 1.20.0 (2020-11-03).  It will eventually become _defunct_ and removed.  The background for this can be found in <https://github.com/HenrikBengtsson/future/issues/420>.

Your **protti** package relies on `multiprocess`, cf. <https://github.com/jpquast/protti/search?q=multiprocess>.

Please migrate your code to the platform-independent `plan(multisession)` or the Linux/macOS-specific `plan(multicore)`.  If you want to emulate what `multiprocess` does, you can do something like:

```r
  if (parallelly::supportsMulticore()) {
    oplan <- plan(multicore)
  } else {
    oplan <- plan(multisession)
  }
  on.exit(plan(oplan))
```

BTW, if you don't already do so, please make sure to undo any `plan()` you set in your code, as illustrated by the above example.  This is needed to guarantee that calling your code won't override settings that the user has set previously.  You can read about this in <https://future.futureverse.org/reference/plan.html#for-package-developers>.

Thank you,

Henrik
(maintainer of the **future** package)

**Comment by jpquast** [comment]
Thank you for the heads up!
This has been resolved in pull request #161.
