### ISSUE TITLE
Fetch uniprot functions need to be updated

### ISSUE THREAD

**Issue by dschust-r** [jpquast/protti#176]
UniProt recently updated their website and changed the way it is accessed programmatically. In order to ensure that everything works as it used to, we need to update our `fetch_uniprot` and `fetch_uniprot_proteome` functions. As a quick fix we have updated these functions to retrieve information from the UniProt legacy website. These changes are not implemented on CRAN yet.

**Comment by jpquast** [comment]
The new API format has been implemented in #179.
