### ISSUE TITLE
confusions about the qc_sample_correlation function 

### ISSUE THREAD

**Issue by Clovernana** [jpquast/protti#177]
I have tried many times using "qc_sample_correlation" function to calculate correlation level but an error occurs always. 
I have comapred my data with the example data and found nothing abnormal in the format. I don't know why for this problem. Could you please help me check this issue? 
I have uploaded top rows of my file here. 
![图片](https://user-images.githubusercontent.com/50875585/185075388-e5771c6e-0a26-4995-ad5d-5a8d7d1b0ad1.png)

[myfile.csv](https://github.com/jpquast/protti/files/9357990/myfile.csv)

**Comment by dschust-r** [comment]
Hi and thank you for your comment! 

In the csv file you uploaded, you do not have a `peptide_intensity` column. Please also make sure that there is only one intensity associated with one peptide (i.e. if you use the `eg_precursor_id` column, use the `fg_quantity` column; if you use `pep_stripped_sequence,` make sure you use a column that contains the intensity for this peptide and not just the precursors). 

I hope that helps!

**Comment by dschust-r** [comment]
I am closing this issue now and hope that my suggestions could help you!
