### ISSUE TITLE
impute() throws error, even with the example given with create_synthetic_data()

### ISSUE THREAD

**Issue by candidaorelmex** [jpquast/protti#181]
Hi, I really like your package! As the title says, I've encountered an issue - the example I'm referring to is the one given in:
https://rdrr.io/cran/protti/man/impute.html

I have my own data that I wanted to apply impute() on, it threw back an error so I tried to test if the function works with the example you provide. The error is the same in both cases, minding column name differences: 
![image](https://user-images.githubusercontent.com/90688191/190334836-701afe81-71a4-4d15-a67d-2f93945fe0c9.png)
(this is the one recieved when trying to imitate the example with synthetic data)

Is there a bug or am I using the function in a wrong way? The code I ran was:

`
set.seed(123) # Makes example reproducible

data <- create_synthetic_data(
  n_proteins = 10,
  frac_change = 0.5,
  n_replicates = 4,
  n_conditions = 2,
  method = "effect_random",
  additional_metadata = FALSE
)

head(data, n = 24)

data_missing <- assign_missingness(
  data,
  sample = sample,
  condition = condition,
  grouping = peptide,
  intensity = peptide_intensity_missing,
  ref_condition = "all",
  retain_columns = c(protein, peptide_intensity)
)

head(data_missing, n = 24)

data_imputed <- impute(
  data_missing,
  sample = sample,
  grouping = peptide,
  intensity_log2 = peptide_intensity_missing,
  condition = condition,
  comparison = comparison,
  missingness = missingness,
  method = "ludovic",
  retain_columns = c(protein, peptide_intensity)
)

head(data_imputed, n = 24)
`

Thanks for your help and keep up the good work:)

**Comment by jpquast** [comment]
Hi thanks for posting the issue! 
Unfortunately it seems like I cannot reproduce it. Could you maybe post a `sessionInfo()`? Could it be that there are some old packages causing the problem? Do you have the chance to run the same on a different computer to rule out it is a problem of your environment?

``` r
library(protti)
#> Welcome to protti version 0.4.0!
#>                             
#> Have fun analysing your data!
set.seed(123) # Makes example reproducible

data <- create_synthetic_data(
    n_proteins = 10,
    frac_change = 0.5,
    n_replicates = 4,
    n_conditions = 2,
    method = "effect_random",
    additional_metadata = FALSE
)

head(data, n = 24)
#> # A tibble: 24 × 8
#>    protein   peptide     condition sample peptide_intensi… change change_peptide
#>    <chr>     <chr>       <chr>     <chr>             <dbl> <lgl>  <lgl>         
#>  1 protein_1 peptide_1_1 conditio… sampl…             16.8 TRUE   TRUE          
#>  2 protein_1 peptide_1_1 conditio… sampl…             17.0 TRUE   TRUE          
#>  3 protein_1 peptide_1_1 conditio… sampl…             17.0 TRUE   TRUE          
#>  4 protein_1 peptide_1_1 conditio… sampl…             17.0 TRUE   TRUE          
#>  5 protein_1 peptide_1_1 conditio… sampl…             15.8 TRUE   TRUE          
#>  6 protein_1 peptide_1_1 conditio… sampl…             15.9 TRUE   TRUE          
#>  7 protein_1 peptide_1_1 conditio… sampl…             16.1 TRUE   TRUE          
#>  8 protein_1 peptide_1_1 conditio… sampl…             15.9 TRUE   TRUE          
#>  9 protein_1 peptide_1_2 conditio… sampl…             12.6 TRUE   FALSE         
#> 10 protein_1 peptide_1_2 conditio… sampl…             12.7 TRUE   FALSE         
#> # … with 14 more rows, and 1 more variable: peptide_intensity_missing <dbl>

data_missing <- assign_missingness(
    data,
    sample = sample,
    condition = condition,
    grouping = peptide,
    intensity = peptide_intensity_missing,
    ref_condition = "all",
    retain_columns = c(protein, peptide_intensity)
)
#> "all" was provided as reference condition. All pairwise comparisons are
#> created from the conditions and assigned their missingness. The created
#> comparisons are:
#> condition_1_vs_condition_2

head(data_missing, n = 24)
#> # A tibble: 24 × 8
#>    protein peptide_intensi… sample condition peptide peptide_intensi… comparison
#>    <chr>              <dbl> <chr>  <chr>     <chr>              <dbl> <chr>     
#>  1 protei…             16.8 sampl… conditio… peptid…             16.8 condition…
#>  2 protei…             17.0 sampl… conditio… peptid…             17.0 condition…
#>  3 protei…             17.0 sampl… conditio… peptid…             17.0 condition…
#>  4 protei…             17.0 sampl… conditio… peptid…             17.0 condition…
#>  5 protei…             15.8 sampl… conditio… peptid…             15.8 condition…
#>  6 protei…             15.9 sampl… conditio… peptid…             15.9 condition…
#>  7 protei…             16.1 sampl… conditio… peptid…             16.1 condition…
#>  8 protei…             15.9 sampl… conditio… peptid…             15.9 condition…
#>  9 protei…             12.6 sampl… conditio… peptid…             NA   condition…
#> 10 protei…             12.7 sampl… conditio… peptid…             NA   condition…
#> # … with 14 more rows, and 1 more variable: missingness <chr>

data_imputed <- impute(
    data_missing,
    sample = sample,
    grouping = peptide,
    intensity_log2 = peptide_intensity_missing,
    condition = condition,
    comparison = comparison,
    missingness = missingness,
    method = "ludovic",
    retain_columns = c(protein, peptide_intensity)
)

head(data_imputed, n = 24)
#> # A tibble: 24 × 10
#>    protein peptide_intensi… sample condition peptide peptide_intensi… comparison
#>    <chr>              <dbl> <chr>  <chr>     <chr>              <dbl> <chr>     
#>  1 protei…             16.8 sampl… conditio… peptid…             16.8 condition…
#>  2 protei…             17.0 sampl… conditio… peptid…             17.0 condition…
#>  3 protei…             17.0 sampl… conditio… peptid…             17.0 condition…
#>  4 protei…             17.0 sampl… conditio… peptid…             17.0 condition…
#>  5 protei…             15.8 sampl… conditio… peptid…             15.8 condition…
#>  6 protei…             15.9 sampl… conditio… peptid…             15.9 condition…
#>  7 protei…             16.1 sampl… conditio… peptid…             16.1 condition…
#>  8 protei…             15.9 sampl… conditio… peptid…             15.9 condition…
#>  9 protei…             12.6 sampl… conditio… peptid…             NA   condition…
#> 10 protei…             12.7 sampl… conditio… peptid…             NA   condition…
#> # … with 14 more rows, and 3 more variables: missingness <chr>,
#> #   imputed_intensity <dbl>, imputed <lgl>
```

<sup>Created on 2022-09-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by candidaorelmex** [comment]
Sure! Here my sessionInfo()

![image](https://user-images.githubusercontent.com/90688191/190367179-842f2887-fe98-4c0b-b7cb-f35082293d20.png)

ill check if I the problem persists on a different computer.

Thanks for your help!

**Comment by jpquast** [comment]
There is nothing obvious that I can see from the `sessionInfo()`, but protti doesn't seem to be loaded here. Did you have the chance to test it on another computer?

**Comment by jpquast** [comment]
@candidaorelmex Did you have a chance to try this again? Did you resolve the problem?

**Comment by candidaorelmex** [comment]
I'm sorry for the delayed response.

I wasn't able to reproduce the error anymore, I still don't know what went wrong back then. Data imputation seems to work fine now.

Thanks a lot for your help, and again sorry for taking this long to answer.

**Comment by jpquast** [comment]
Okay great! No worries! Happy that it works!
