### ISSUE TITLE
volcano_plot() function fails when there is no significant peptide after p-value adjustment

### ISSUE THREAD

**Issue by AnnaPagotto** [jpquast/protti#190]
Hi guys,
I noticed that if there is no significant peptide after p-value adjustment, the `volcano_plot()` function fails, BUT ONLY WHEN THE    ``interactive =`` ARGUMENT IS GIVEN.
Could you please give it a look?
Thankssss :)

**Comment by jpquast** [comment]
Fixed this in PR #191.
