### ISSUE TITLE
qc_proteome_coverage: labels linked to wrong colors

### ISSUE THREAD

**Issue by SabrinaKeller** [jpquast/protti#194]
the labels in the plot for the proteome coverage (qc_proteome_coverage) are linked to the wrong color in the plot legend. 

![image](https://user-images.githubusercontent.com/44097032/223691057-a5f796e8-0060-4cf5-927a-eb498d808b73.png)

![image](https://user-images.githubusercontent.com/44097032/223691142-33e0e3de-b530-4f59-8004-94908bb21e4b.png)

labels = c("proteins_detected" = "detected", "proteins_undetected" = "not detected") fixes the issue

**Comment by jpquast** [comment]
Fixed in PR #219.
