### ISSUE TITLE
documentation calculate_protein_abundance() 

### ISSUE THREAD

**Issue by AnnaPagotto** [jpquast/protti#195]
Dear fellow colleagues,
I found a mistake in the documentation of the function `calculate_protein_abundance()`:

> If for_plot = FALSE, protein abundances are returned, if for_plot = TRUE also precursor intensities are returned in a data frame. The later output is ideal for plotting with **qc_protein_abundance** and can be filtered to only include protein abundances.

that should be:

> If `for_plot = FALSE`, protein abundances are returned, if `for_plot = TRUE` also precursor intensities are returned in a data frame. The later output is ideal for plotting with `peptide_profile_plot()` and can be filtered to only include protein abundances.

Thank you for your great work 🥇 

Anna

**Comment by jpquast** [comment]
This was fixed in PR #219.
