### ISSUE TITLE
Partial output of fetch_uniprot.R

### ISSUE THREAD

**Issue by ThorbenSchramm** [jpquast/protti#203]
It seems that "fetch_uniprot.R" provides a partial output even if some of the batches fail to download data from uniprot (due to high traffic: "HTTP ERROR 429"). If using markdowns, the console warnings are easily overlooked. I would suggest that the function should only provide an output if all batches are successfully downloaded.

**Comment by jpquast** [comment]
This was changed in protti version 0.8.0 in PR #234.
