### ISSUE TITLE
'Timeout is reached' in fetch_uniprot

### ISSUE THREAD

**Issue by She1111** [jpquast/protti#205]
Hi,

In my dataset there are more than 4000 proteins ID going to retrieve from Uniprot. When I use fetch_uniprot() function, it comes
```shell
Please note that some column names have changed due to UniProt updating its API! This might cause errors in your code. You can fix it by replacing the old column names with new ones.
The following IDs have not been retrieved correctly.                                                                                   
# A tibble: 10 × 2
   id                error                                                                                                     
   <chr>             <chr>                                                                                                     
 1 IDs: 1 to 200     Timeout was reached: [rest.uniprot.org] Operation timed out after 30001 milliseconds with 0 bytes received
``` 

Could you give me some advice about this issue please?
Thanks in advance!

Best regards,
Shel

**Comment by dschust-r** [comment]
Dear Shel, 

Can you maybe try again? 
I think this could be either related to your internet connection or an issue with UniProt. 
I had the same issue just running it on a test data set with ca. 4000 proteins. After closing all my Google Chrome tabs and trying again it worked for me. 

Please let me know if this worked for you. 

All the best, 
Dina

**Comment by She1111** [comment]
> Dear Shel,
> 
> Can you maybe try again? I think this could be either related to your internet connection or an issue with UniProt. I had the same issue just running it on a test data set with ca. 4000 proteins. After closing all my Google Chrome tabs and trying again it worked for me.
> 
> Please let me know if this worked for you.
> 
> All the best, Dina

Hi Dina,

Thank you for your quick reply! I would like to try it again in the late afternoon as the network is not that busy :)!

Best,
Shel

**Comment by She1111** [comment]
Hi Dina,

It works! Thanks again :)!
💯 

Best,
Shel

**Comment by She1111** [comment]
Hi Dina,

I got another problem when I used 'fetch_uniprot' function. It reported 'Client error: (400) Bad Request'. Is this issue the same as the above one? 

Best,
Shel

**Comment by dschust-r** [comment]
Hi Shel, 

Can you provide examples of how you are trying to run the functions or can you try to run the examples we have listed for the functions? You will find them with `?fetch_uniprot` or `?calculate_sequence_coverage` at the bottom of the function documentation. 

I just tried the `fetch_uniprot()` function and it works for me, maybe you could try to start a new R session?

**Comment by She1111** [comment]
Hi Dina,

Maybe there is also some problems happening about the internet when I use 'fetch_uniprot'. It works well now.
Here is the manusctrip:

```r
#Fetching database information and assigning peptide types
uniprot_ids <- unique(data$protein_id)

uniprot <-
  fetch_uniprot(
    uniprot_ids = uniprot_ids,
    columns = c(
      "protein_name",
      "gene_names",
      "go_f",
      "xref_sliing",
      "cc_interaction",
      "ft_act_site",
      "ft_binding",
      "xref_pdb",
      "length",
      "sequence"
    )
  ) %>% 
  rename(protein_id = accession, protein_sequence = sequence)

data_filtered_uniprot <- data %>%
  left_join(y = uniprot,
            by = "protein_id") %>%
  find_peptide(protein_sequence = protein_sequence,
               peptide_sequence = peptide_sequence) %>%
  assign_peptide_type(aa_before = aa_before,
                      last_aa = last_aa, 
                      aa_after = aa_after) %>%
  calculate_sequence_coverage(protein_sequence = protein_sequence,
                              peptides = peptide_sequence)
``` 
Everythins works well except 'calculate_sequence_coverage'. That means if I only run 'data_filtered_uniprot <- data %>%
  left_join(y = uniprot,
            by = "protein_id") %>%
  find_peptide(protein_sequence = protein_sequence,
               peptide_sequence = peptide_sequence) %>%
  assign_peptide_type(aa_before = aa_before,
                      last_aa = last_aa, 
                      aa_after = aa_after)',
it works.
Thank you for your help!

Best,
Shel

**Comment by dschust-r** [comment]
Happy to hear that `fetch_uniprot()` now works again, this can definitely be related to the internet connection.

Concerning `calculate_sequence_coverage()`: can you maybe check if you have identified peptides for the protein with the sequence "MAIMSDLPRDLLAEILSRVPLASLRSVRFTCKKWNDLSKDRSFLKKQIVEAKKKQLKSKEFEVIMMRNFRVYLTSVDLHNDVNPSFTPKGTLTSFSDDANQHQVDNVSSVFHCDGLLLCITKDLNFRLVVWNPYFGQTRWIQPRNSYHIKDIYAIGYDENKNHKILRLKDQYYDYDSHPRARICEFELYSFESNSWKVVLDVSPDWYIHSYHRGLSVKGNTYWYATEKHGYVNFLICFDFTTEKFGPRLPLPFNATESFTYDDVVTLSSVGEEQLALLFQSDATLMMEIWVTSKVDPTEVLWNKLFLAVDHDMIEFDYELKFVADAGSFFIDQKKNVVVVFDKDMNEHTHRGMAYIVGKNGYFKRVDIGEEAYTSCFPLVCSYVPSSVQIRQLT" that don't make any sense?

I managed to reproduce your error message when looking for peptides in a sequence that cannot be identified: 

```
> data <- data.frame(
+     protein_sequence = c("abcdefghijklmnop", "abcdefghijklmnop"),
+     pep_stripped_sequence = c("yzz", "yz")
+ )
> calculate_sequence_coverage(
+     data,
+     protein_sequence = protein_sequence,
+     peptides = pep_stripped_sequence
+ )
Error in `dplyr::mutate()`:
ℹ In argument: `modified_sequence = replace_identified_by_x(protein_sequence, .data$start, .data$end)`.
ℹ In group 1: `protein_sequence = "abcdefghijklmnop"`.
Caused by error in `result[[length(result)]]`:
! attempt to select less than one element in integerOneIndex
Run `rlang::last_trace()` to see where the error occurred.
```

**Comment by She1111** [comment]
Hi Dina,

Yes, there is NA value about this protein. Maybe we have to filter out this missing values before calculate coverage. I add 
```rfilter()``` command in and it works. Is that correct?
```r
data_filtered_uniprot <- data %>%
  left_join(y = uniprot,
            by = "protein_id") %>%
  find_peptide(protein_sequence = protein_sequence,
               peptide_sequence = peptide_sequence) %>%
  assign_peptide_type(aa_before = aa_before,
                      last_aa = last_aa, 
                      aa_after = aa_after) %>%
  filter(pep_type != "NA") %>%
  calculate_sequence_coverage(protein_sequence = protein_sequence,
                              peptides = peptide_sequence)
```

Best,
Shel

**Comment by dschust-r** [comment]
Great that this works now! 

I would probably remove the NAs in the `peptide_sequence` column directly and not in the `pep_type` column but otherwise this looks fine to me. The result should be similar though: if you did not have a peptide sequence to begin with, you should also not get a peptide type.

**Comment by She1111** [comment]
> Great that this works now!
> 
> I would probably remove the NAs in the `peptide_sequence` column directly and not in the `pep_type` column but otherwise this looks fine to me. The result should be similar though: if you did not have a peptide sequence to begin with, you should also not get a peptide type.

It is strange it does have 'peptide_sequence' before. But the column of 'prev_aa' and 'after_aa' also gave 'NA' value in the original output (I use fragpipe as searching engine). I also can filter these rows out before analysing. Happy that it works now!
Thank you so much :)!

Best,
Shel

**Comment by dschust-r** [comment]
That is indeed strange and sounds like the peptide sequences are not in your protein sequence. Did you check if this only occurs for this one protein? I just hope this does not remove any proteins you might be interested in.

**Comment by She1111** [comment]
Yes I agree. I search these peptides (with 'NA' value) in Uniprot and find there is wrong matching! This may caused by searching engine!
<img width="914" alt="Capture" src="https://github.com/jpquast/protti/assets/130647208/dc8e170a-2cd6-4ed0-b8ee-6a4ae1b59c0c">
<img width="934" alt="Capture1" src="https://github.com/jpquast/protti/assets/130647208/3b71d82e-4a69-40ac-9832-8d0dafdd009e">


Best,
Shel

**Comment by dschust-r** [comment]
Definitely good to be aware of this when you analyze your data, I hope there's not too many of them. 
Anyway, happy we could figure out that this is not related to the `calculate_sequence_coverage()` function 😄
