### ISSUE TITLE
fetch_kegg.R doesnt join dataframe correctly

### ISSUE THREAD

**Issue by elena-krismer** [jpquast/protti#217]
<img width="453" alt="Screenshot 2023-11-03 at 10 00 46" src="https://github.com/jpquast/protti/assets/70535771/428d3351-b86a-4351-8503-85d62a431e82">
 the fetch_kegg function is buggy - and returns NA in the pathway column - causing our github actions to fail

**Comment by jpquast** [comment]
I thought I fixed something in this function recently but maybe they updated it again since then. But it could be that the fix was in the fix issues PR.

**Comment by elena-krismer** [comment]
fixed in #201

**Comment by elena-krismer** [comment]
fixed in #201

**Comment by elena-krismer** [comment]
fixed in #201
