### ISSUE TITLE
fetch_uniprot accession

### ISSUE THREAD

**Issue by jpquast** [jpquast/protti#245]
`fetch_uniprot()` finds a valid UniProt accession in for example: "CON_ENSEMBL:ENSBTAP00000037665", which is wrong.

**Comment by jinaanna** [comment]
When will the bug be fixed? This function cannot be used normally.

**Comment by jpquast** [comment]
My solution to this problem would be to not allow any letters or numbers before or after the recognised UniProt accession. In which cases does it go wrong for you @jinaanna? Would that fix the problem for you too?

**Comment by jpquast** [comment]
@jinaanna I fixed the bug in the developer version already. You can download that by using `devtools::install_github("jpquast/protti", ref = "developer")`.

**Comment by jpquast** [comment]
Has been fixed in #250
